###
PUT http://localhost:1000/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmdvIFZpZXQgVGllbiAoSzE2X0hDTSkiLCJlbWFpbCI6InRpZW5udnNlMTYxMjA0QGZwdC5lZHUudm4iLCJpYXQiOjE2MzQ0NzM4NzV9.BJ43Cq3ugFVCvTkcs0RXa-3YQZ3I2SvZSfTnJTV0RJM
Content-Type: application/json

{
    "phone": "0903678282",
    "name": "Ngô Việt Tiến",
    "studentCode": "se161204",
    "major": "Kĩ thuật phần mềm",
    "semester": "LUK 6"
}

###
GET http://localhost:1000/auth/getStep
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTmdvIFZpZXQgVGllbiAoSzE2X0hDTSkiLCJlbWFpbCI6InRpZW5udnNlMTYxMjA0QGZwdC5lZHUudm4iLCJpYXQiOjE2MzQ1NjY5NzF9.0LkAq3YULf8K15lgWIFwFCwZcInC5f7Lf3qR6ezQbwY